#ifndef __PCL_REALSENSE2_PRESET_H__
#define __PCL_REALSENSE2_PRESET_H__
#pragma once
// std
#include <string>
namespace pcl {
	namespace io {
		namespace realsense2 {
			const std::string HIGH_RES_HIGH_DENSITY_PRESET =
				"{"
				"\"param-disableraucolor\": 0,"
				"\"param-disablesadcolor\": 0,"
				"\"param-disablesadnormalize\": 0,"
				"\"param-disablesloleftcolor\": 0,"
				"\"param-disableslorightcolor\": 0,"
				"\"param-lambdaad\": 618,"
				"\"param-lambdacensus\": 15,"
				"\"param-leftrightthreshold\": 18,"
				"\"param-maxscorethreshb\": 1443,"
				"\"param-medianthreshold\": 789,"
				"\"param-minscorethresha\": 96,"
				"\"param-neighborthresh\": 12,"
				"\"param-raumine\": 2,"
				"\"param-rauminn\": 1,"
				"\"param-rauminnssum\": 6,"
				"\"param-raumins\": 3,"
				"\"param-rauminw\": 3,"
				"\"param-rauminwesum\": 7,"
				"\"param-regioncolorthresholdb\": 0.11028557924300367,"
				"\"param-regioncolorthresholdg\": 0.5729592245318832,"
				"\"param-regioncolorthresholdr\": 0.017746482533836073,"
				"\"param-regionshrinku\": 4,"
				"\"param-regionshrinkv\": 0,"
				"\"param-regionspatialthresholdu\": 7,"
				"\"param-regionspatialthresholdv\": 3,"
				"\"param-robbinsmonrodecrement\": 6,"
				"\"param-robbinsmonroincrement\": 21,"
				"\"param-rsmdiffthreshold\": 1.228300048811172,"
				"\"param-rsmrauslodiffthreshold\": 0.26648832912881404,"
				"\"param-rsmremovethreshold\": 0.4935489490398768,"
				"\"param-scanlineedgetaub\": 8,"
				"\"param-scanlineedgetaug\": 200,"
				"\"param-scanlineedgetaur\": 279,"
				"\"param-scanlinep1\": 55,"
				"\"param-scanlinep1onediscon\": 326,"
				"\"param-scanlinep1twodiscon\": 134,"
				"\"param-scanlinep2\": 235,"
				"\"param-scanlinep2onediscon\": 506,"
				"\"param-scanlinep2twodiscon\": 206,"
				"\"param-secondpeakdelta\": 222,"
				"\"param-texturecountthresh\": 0,"
				"\"param-texturedifferencethresh\": 2466,"
				"\"param-usersm\": 1"
				"}";
			const std::string MED_RES_HIGH_DENSITY_PRESET = 
				"{"
				"\"param-censususize\": 9,"
				"\"param-censusvsize\": 3,"
				"\"param-disableraucolor\": 0,"
				"\"param-disablesadcolor\": 0,"
				"\"param-disablesadnormalize\": 0,"
				"\"param-disablesloleftcolor\": 1,"
				"\"param-disableslorightcolor\": 0,"
				"\"param-lambdaad\": 850,"
				"\"param-lambdacensus\": 19,"
				"\"param-leftrightthreshold\": 32,"
				"\"param-maxscorethreshb\": 1949,"
				"\"param-medianthreshold\": 276,"
				"\"param-minscorethresha\": 68,"
				"\"param-neighborthresh\": 4,"
				"\"param-raumine\": 7,"
				"\"param-rauminn\": 1,"
				"\"param-rauminnssum\": 6,"
				"\"param-raumins\": 3,"
				"\"param-rauminw\": 6,"
				"\"param-rauminwesum\": 14,"
				"\"param-regioncolorthresholdb\": 0.011669743090467342,"
				"\"param-regioncolorthresholdg\": 0.6462791871946363,"
				"\"param-regioncolorthresholdr\": 0.017414829649508693,"
				"\"param-regionshrinku\": 4,"
				"\"param-regionshrinkv\": 1,"
				"\"param-regionspatialthresholdu\": 7,"
				"\"param-regionspatialthresholdv\": 3,"
				"\"param-robbinsmonrodecrement\": 1,"
				"\"param-robbinsmonroincrement\": 4,"
				"\"param-rsmdiffthreshold\": 5.06979466489835,"
				"\"param-rsmrauslodiffthreshold\": 1.0,"
				"\"param-rsmremovethreshold\": 0.4474719403505988,"
				"\"param-scanlineedgetaub\": 4,"
				"\"param-scanlineedgetaug\": 542,"
				"\"param-scanlineedgetaur\": 982,"
				"\"param-scanlinep1\": 479,"
				"\"param-scanlinep1onediscon\": 4,"
				"\"param-scanlinep1twodiscon\": 25,"
				"\"param-scanlinep2\": 342,"
				"\"param-scanlinep2onediscon\": 69,"
				"\"param-scanlinep2twodiscon\": 225,"
				"\"param-secondpeakdelta\": 6,"
				"\"param-texturecountthresh\": 1,"
				"\"param-texturedifferencethresh\": 0,"
				"\"param-usersm\": 1"
				"}";
			const std::string LOW_RES_HIGH_DENSITY_PRESET = 
				"{"
				"\"param-censususize\": 9,"
				"\"param-censusvsize\" : 9,"
				"\"param-disableraucolor\" : 0,"
				"\"param-disablesadcolor\" : 0,"
				"\"param-disablesadnormalize\" : 0,"
				"\"param-disablesloleftcolor\" : 1,"
				"\"param-disableslorightcolor\" : 0,"
				"\"param-lambdaad\" : 686,"
				"\"param-lambdacensus\" : 26,"
				"\"param-leftrightthreshold\" : 20,"
				"\"param-maxscorethreshb\" : 3440,"
				"\"param-medianthreshold\" : 973,"
				"\"param-minscorethresha\" : 90,"
				"\"param-neighborthresh\" : 91,"
				"\"param-raumine\" : 1,"
				"\"param-rauminn\" : 1,"
				"\"param-rauminnssum\" : 5,"
				"\"param-raumins\" : 2,"
				"\"param-rauminw\" : 6,"
				"\"param-rauminwesum\" : 4,"
				"\"param-regioncolorthresholdb\" : 0.29367143700253656,"
				"\"param-regioncolorthresholdg\" : 0.012504143377510591,"
				"\"param-regioncolorthresholdr\" : 0.05893324447962866,"
				"\"param-regionshrinku\" : 4,"
				"\"param-regionshrinkv\" : 1,"
				"\"param-regionspatialthresholdu\" : 7,"
				"\"param-regionspatialthresholdv\" : 3,"
				"\"param-robbinsmonrodecrement\" : 2,"
				"\"param-robbinsmonroincrement\" : 18,"
				"\"param-rsmdiffthreshold\" : 5.89083925111254,"
				"\"param-rsmrauslodiffthreshold\" : 0.421688050845725,"
				"\"param-rsmremovethreshold\" : 0.4062114741986549,"
				"\"param-scanlineedgetaub\" : 105,"
				"\"param-scanlineedgetaug\" : 60,"
				"\"param-scanlineedgetaur\" : 64,"
				"\"param-scanlinep1\" : 170,"
				"\"param-scanlinep1onediscon\" : 67,"
				"\"param-scanlinep1twodiscon\" : 59,"
				"\"param-scanlinep2\" : 386,"
				"\"param-scanlinep2onediscon\" : 86,"
				"\"param-scanlinep2twodiscon\" : 60,"
				"\"param-secondpeakdelta\" : 463,"
				"\"param-texturecountthresh\" : 0,"
				"\"param-texturedifferencethresh\" : 3639,"
				"\"param-usersm\" : 1,"
				"\"result\" : -69.05536699602217"
				"}";
			const std::string HIGH_RES_MED_DENSITY_PRESET =
				"{"
				"\"param-disableraucolor\": 0,"
				"\"param-disablesadcolor\" : 0,"
				"\"param-disablesadnormalize\" : 0,"
				"\"param-disablesloleftcolor\" : 0,"
				"\"param-disableslorightcolor\" : 1,"
				"\"param-lambdaad\" : 935,"
				"\"param-lambdacensus\" : 26,"
				"\"param-leftrightthreshold\" : 19,"
				"\"param-maxscorethreshb\" : 887,"
				"\"param-medianthreshold\" : 1021,"
				"\"param-minscorethresha\" : 54,"
				"\"param-neighborthresh\" : 97,"
				"\"param-raumine\" : 3,"
				"\"param-rauminn\" : 1,"
				"\"param-rauminnssum\" : 6,"
				"\"param-raumins\" : 3,"
				"\"param-rauminw\" : 5,"
				"\"param-rauminwesum\" : 11,"
				"\"param-regioncolorthresholdb\" : 0.014525116743001514,"
				"\"param-regioncolorthresholdg\" : 0.7081795895730004,"
				"\"param-regioncolorthresholdr\" : 0.18219370378688518,"
				"\"param-regionshrinku\" : 3,"
				"\"param-regionshrinkv\" : 1,"
				"\"param-regionspatialthresholdu\" : 7,"
				"\"param-regionspatialthresholdv\" : 3,"
				"\"param-robbinsmonrodecrement\" : 23,"
				"\"param-robbinsmonroincrement\" : 3,"
				"\"param-rsmdiffthreshold\" : 1.816745640601172,"
				"\"param-rsmrauslodiffthreshold\" : 1.0,"
				"\"param-rsmremovethreshold\" : 0.48617561168925416,"
				"\"param-scanlineedgetaub\" : 16,"
				"\"param-scanlineedgetaug\" : 259,"
				"\"param-scanlineedgetaur\" : 896,"
				"\"param-scanlinep1\" : 132,"
				"\"param-scanlinep1onediscon\" : 77,"
				"\"param-scanlinep1twodiscon\" : 234,"
				"\"param-scanlinep2\" : 342,"
				"\"param-scanlinep2onediscon\" : 390,"
				"\"param-scanlinep2twodiscon\" : 151,"
				"\"param-secondpeakdelta\" : 600,"
				"\"param-texturecountthresh\" : 0,"
				"\"param-texturedifferencethresh\" : 0,"
				"\"param-usersm\" : 1"
				"}";
			const std::string MED_RES_MED_DENSITY_PRESET = 
				"{"
				"\"param-censususize\": 8,"
				"\"param-censusvsize\" : 5,"
				"\"param-disableraucolor\" : 0,"
				"\"param-disablesadcolor\" : 0,"
				"\"param-disablesadnormalize\" : 0,"
				"\"param-disablesloleftcolor\" : 1,"
				"\"param-disableslorightcolor\" : 0,"
				"\"param-lambdaad\" : 978,"
				"\"param-lambdacensus\" : 21,"
				"\"param-leftrightthreshold\" : 32,"
				"\"param-maxscorethreshb\" : 972,"
				"\"param-medianthreshold\" : 175,"
				"\"param-minscorethresha\" : 3,"
				"\"param-neighborthresh\" : 1,"
				"\"param-raumine\" : 3,"
				"\"param-rauminn\" : 1,"
				"\"param-rauminnssum\" : 6,"
				"\"param-raumins\" : 2,"
				"\"param-rauminw\" : 1,"
				"\"param-rauminwesum\" : 5,"
				"\"param-regioncolorthresholdb\" : 0.6774716242429242,"
				"\"param-regioncolorthresholdg\" : 0.012306832764202736,"
				"\"param-regioncolorthresholdr\" : 0.07908179523435015,"
				"\"param-regionshrinku\" : 4,"
				"\"param-regionshrinkv\" : 1,"
				"\"param-regionspatialthresholdu\" : 7,"
				"\"param-regionspatialthresholdv\" : 3,"
				"\"param-robbinsmonrodecrement\" : 14,"
				"\"param-robbinsmonroincrement\" : 22,"
				"\"param-rsmdiffthreshold\" : 5.859616082943054,"
				"\"param-rsmrauslodiffthreshold\" : 1.0,"
				"\"param-rsmremovethreshold\" : 0.4213190644069522,"
				"\"param-scanlineedgetaub\" : 18,"
				"\"param-scanlineedgetaug\" : 493,"
				"\"param-scanlineedgetaur\" : 390,"
				"\"param-scanlinep1\" : 134,"
				"\"param-scanlinep1onediscon\" : 10,"
				"\"param-scanlinep1twodiscon\" : 70,"
				"\"param-scanlinep2\" : 397,"
				"\"param-scanlinep2onediscon\" : 21,"
				"\"param-scanlinep2twodiscon\" : 226,"
				"\"param-secondpeakdelta\" : 3,"
				"\"param-texturecountthresh\" : 6,"
				"\"param-texturedifferencethresh\" : 0,"
				"\"param-usersm\" : 1"
				"}";
			const std::string LOW_RES_MED_DENSITY_PRESET = 
				"{"
				"\"param-censususize\": 9,"
				"\"param-censusvsize\" : 9,"
				"\"param-disableraucolor\" : 0,"
				"\"param-disablesadcolor\" : 0,"
				"\"param-disablesadnormalize\" : 0,"
				"\"param-disablesloleftcolor\" : 0,"
				"\"param-disableslorightcolor\" : 0,"
				"\"param-lambdaad\" : 183,"
				"\"param-lambdacensus\" : 26,"
				"\"param-leftrightthreshold\" : 30,"
				"\"param-maxscorethreshb\" : 1885,"
				"\"param-medianthreshold\" : 696,"
				"\"param-minscorethresha\" : 43,"
				"\"param-neighborthresh\" : 43,"
				"\"param-raumine\" : 6,"
				"\"param-rauminn\" : 1,"
				"\"param-rauminnssum\" : 2,"
				"\"param-raumins\" : 3,"
				"\"param-rauminw\" : 7,"
				"\"param-rauminwesum\" : 7,"
				"\"param-regioncolorthresholdb\" : 0.05,"
				"\"param-regioncolorthresholdg\" : 0.03092604847265814,"
				"\"param-regioncolorthresholdr\" : 0.41507045973435736,"
				"\"param-regionshrinku\" : 4,"
				"\"param-regionshrinkv\" : 1,"
				"\"param-regionspatialthresholdu\" : 7,"
				"\"param-regionspatialthresholdv\" : 3,"
				"\"param-robbinsmonrodecrement\" : 9,"
				"\"param-robbinsmonroincrement\" : 16,"
				"\"param-rsmdiffthreshold\" : 6.447234381771916,"
				"\"param-rsmrauslodiffthreshold\" : 0.2744664270016177,"
				"\"param-rsmremovethreshold\" : 0.5661915140248058,"
				"\"param-scanlineedgetaub\" : 69,"
				"\"param-scanlineedgetaug\" : 72,"
				"\"param-scanlineedgetaur\" : 124,"
				"\"param-scanlinep1\" : 117,"
				"\"param-scanlinep1onediscon\" : 33,"
				"\"param-scanlinep1twodiscon\" : 64,"
				"\"param-scanlinep2\" : 410,"
				"\"param-scanlinep2onediscon\" : 80,"
				"\"param-scanlinep2twodiscon\" : 74,"
				"\"param-secondpeakdelta\" : 476,"
				"\"param-texturecountthresh\" : 0,"
				"\"param-texturedifferencethresh\" : 2817,"
				"\"param-usersm\" : 1,"
				"\"result\" : -71.79800597031867"
				"}";
			const std::string HIGH_RES_HIGH_ACCURACY_PRESET =
				"{"
				"\"param-disableraucolor\": 0,"
				"\"param-disablesadcolor\": 0,"
				"\"param-disablesadnormalize\": 0,"
				"\"param-disablesloleftcolor\": 0,"
				"\"param-disableslorightcolor\": 1,"
				"\"param-lambdaad\": 751,"
				"\"param-lambdacensus\": 6,"
				"\"param-leftrightthreshold\": 10,"
				"\"param-maxscorethreshb\": 2893,"
				"\"param-medianthreshold\": 796,"
				"\"param-minscorethresha\": 4,"
				"\"param-neighborthresh\": 108,"
				"\"param-raumine\": 6,"
				"\"param-rauminn\": 3,"
				"\"param-rauminnssum\": 7,"
				"\"param-raumins\": 2,"
				"\"param-rauminw\": 2,"
				"\"param-rauminwesum\": 12,"
				"\"param-regioncolorthresholdb\": 0.786380709066072,"
				"\"param-regioncolorthresholdg\": 0.5664810046339115,"
				"\"param-regioncolorthresholdr\": 0.9857413557742051,"
				"\"param-regionshrinku\": 3,"
				"\"param-regionshrinkv\": 0,"
				"\"param-regionspatialthresholdu\": 7,"
				"\"param-regionspatialthresholdv\": 3,"
				"\"param-robbinsmonrodecrement\": 25,"
				"\"param-robbinsmonroincrement\": 2,"
				"\"param-rsmdiffthreshold\": 1.6605679586483368,"
				"\"param-rsmrauslodiffthreshold\": 0.7269914923801174,"
				"\"param-rsmremovethreshold\": 0.8150280066589434,"
				"\"param-scanlineedgetaub\": 13,"
				"\"param-scanlineedgetaug\": 15,"
				"\"param-scanlineedgetaur\": 30,"
				"\"param-scanlinep1\": 155,"
				"\"param-scanlinep1onediscon\": 160,"
				"\"param-scanlinep1twodiscon\": 59,"
				"\"param-scanlinep2\": 190,"
				"\"param-scanlinep2onediscon\": 507,"
				"\"param-scanlinep2twodiscon\": 493,"
				"\"param-secondpeakdelta\": 647,"
				"\"param-texturecountthresh\": 0,"
				"\"param-texturedifferencethresh\": 1722,"
				"\"param-usersm\": 1"
				"}";
			const std::string MED_RES_HIGH_ACCURACY_PRESET = 
				"{"
				"\"param-censususize\": 6,"
				"\"param-censusvsize\" : 7,"
				"\"param-disableraucolor\" : 0,"
				"\"param-disablesadcolor\" : 0,"
				"\"param-disablesadnormalize\" : 0,"
				"\"param-disablesloleftcolor\" : 0,"
				"\"param-disableslorightcolor\" : 0,"
				"\"param-lambdaad\" : 630,"
				"\"param-lambdacensus\" : 26,"
				"\"param-leftrightthreshold\" : 18,"
				"\"param-maxscorethreshb\" : 2047,"
				"\"param-medianthreshold\" : 347,"
				"\"param-minscorethresha\" : 80,"
				"\"param-neighborthresh\" : 82,"
				"\"param-raumine\" : 3,"
				"\"param-rauminn\" : 1,"
				"\"param-rauminnssum\" : 6,"
				"\"param-raumins\" : 2,"
				"\"param-rauminw\" : 2,"
				"\"param-rauminwesum\" : 3,"
				"\"param-regioncolorthresholdb\" : 0.02575965041840711,"
				"\"param-regioncolorthresholdg\" : 0.9545065192180644,"
				"\"param-regioncolorthresholdr\" : 0.028804875070092176,"
				"\"param-regionshrinku\" : 4,"
				"\"param-regionshrinkv\" : 1,"
				"\"param-regionspatialthresholdu\" : 7,"
				"\"param-regionspatialthresholdv\" : 3,"
				"\"param-robbinsmonrodecrement\" : 15,"
				"\"param-robbinsmonroincrement\" : 5,"
				"\"param-rsmdiffthreshold\" : 3.3293430127414756,"
				"\"param-rsmrauslodiffthreshold\" : 0.9618657668112696,"
				"\"param-rsmremovethreshold\" : 0.6703910858723563,"
				"\"param-scanlineedgetaub\" : 442,"
				"\"param-scanlineedgetaug\" : 16,"
				"\"param-scanlineedgetaur\" : 770,"
				"\"param-scanlinep1\" : 21,"
				"\"param-scanlinep1onediscon\" : 3,"
				"\"param-scanlinep1twodiscon\" : 27,"
				"\"param-scanlinep2\" : 182,"
				"\"param-scanlinep2onediscon\" : 41,"
				"\"param-scanlinep2twodiscon\" : 63,"
				"\"param-secondpeakdelta\" : 205,"
				"\"param-texturecountthresh\" : 0,"
				"\"param-texturedifferencethresh\" : 3474,"
				"\"param-usersm\" : 1"
				"}";
			const std::string LOW_RES_HIGH_ACCURACY_PRESET = "";
			const std::string HAND_GESTURE_PRESET = "";
			const std::string D415_REMOVE_IR = "";
			const std::string DEFAULT_PRESET_D415 = "";
			const std::string DEFAULT_PRESET_D435 = 
				"{"
				"\"aux-param-autoexposure-setpoint\": \"1536\","
				"\"aux-param-colorcorrection1\" : \"0.299\","
				"\"aux-param-colorcorrection2\" : \"0.294\","
				"\"aux-param-colorcorrection3\" : \"0.294\","
				"\"aux-param-colorcorrection4\" : \"0.114\","
				"\"aux-param-colorcorrection5\" : \"0.000\","
				"\"aux-param-colorcorrection6\" : \"0.000\","
				"\"aux-param-colorcorrection7\" : \"0.000\","
				"\"aux-param-colorcorrection8\" : \"0.000\","
				"\"aux-param-colorcorrection9\" : \"0.000\","
				"\"aux-param-colorcorrection10\" : \"0.000\","
				"\"aux-param-colorcorrection11\" : \"0.000\","
				"\"aux-param-colorcorrection12\" : \"0.000\","
				"\"aux-param-depthclampmax\" : \"65536\","
				"\"aux-param-depthclampmin\" : \"0\","
				"\"aux-param-disparityshift\" : \"0\","

				"\"param-disableraucolor\" : \"0\","
				"\"param-disablesadcolor\" : \"0\","
				"\"param-disablesadnormalize\" : \"0\","
				"\"param-disablesloleftcolor\" : \"0\","
				"\"param-disableslorightcolor\" : \"0\","
				"\"param-lambdaad\" : \"800\","
				"\"param-lambdacensus\" : \"26\","
				"\"param-leftrightthreshold\" : \"24\","
				"\"param-maxscorethreshb\" : \"2047\","
				"\"param-medianthreshold\" : \"500\","
				"\"param-minscorethresha\" : \"1\","
				"\"param-neighborthresh\" : \"7\","
				"\"param-robbinsmonrodecrement\" : \"10\","
				"\"param-robbinsmonroincrement\" : \"10\","
				"\"param-secondpeakdelta\" : \"325\","
				"\"param-texturecountthresh\" : \"0\","
				"\"param-texturedifferencethresh\" : \"0\","
				"\"param-raumine\" : \"1\","
				"\"param-rauminn\" : \"1\","
				"\"param-rauminnssum\" : \"3\","
				"\"param-raumins\" : \"1\","
				"\"param-rauminw\" : \"1\","
				"\"param-rauminwesum\" : \"3\","
				"\"param-regionshrinku\" : \"3\","
				"\"param-regionshrinkv\" : \"1\","
				"\"param-regioncolorthresholdr\" : \"0.05\","
				"\"param-regioncolorthresholdg\" : \"0.05\","
				"\"param-regioncolorthresholdb\" : \"0.05\","
				"\"param-rsmdiffthreshold\" : \"4\","
				"\"param-rsmrauslodiffthreshold\" : \"1\","
				"\"param-rsmremovethreshold\" : \"0.375\","
				"\"param-usersm\" : \"1\","
				"\"param-scanlineedgetaub\" : \"72\","
				"\"param-scanlineedgetaug\" : \"72\","
				"\"param-scanlineedgetaur\" : \"72\","
				"\"param-scanlinep1\" : \"60\","
				"\"param-scanlinep1onediscon\" : \"105\","
				"\"param-scanlinep1twodiscon\" : \"70\","
				"\"param-scanlinep2\" : \"342\","
				"\"param-scanlinep2onediscon\" : \"190\","
				"\"param-scanlinep2twodiscon\" : \"130\","
				"\"param-censususize\" : \"9\","
				"\"param-censusvsize\" : \"9\","
				"\"param-zunits\" : \"1000\","

				"\"controls-laserstate\" : \"on\","
				"\"controls-laserpower\" : \"150\","
				"\"controls-autoexposure-auto\" : \"True\","
				"\"controls-autoexposure-manual\" : \"8500\","
				"\"controls-depth-gain\" : \"16\""
				"}";
			const std::string SHORT_RANGE_PRESET = "";
			const std::string BODY_SCAN_PRESET = "";
		}
	}
}
#endif // !__PCL_REALSENSE2_PRESET_H__
